CREATE DATABASE truYum;
USE truYum;
SHOW TABLES;
SELECT  database();
CREATE TABLE menu_item(
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
Price INT,
Active VARCHAR(5),
Date_of_Launch DATE,
Category VARCHAR(20),
Free_Delivery VARCHAR(3)
);
DESC USER;
CREATE TABLE user(
Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(20)
);
CREATE TABLE cart(
Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
menu_id INT NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY(menu_id) REFERENCES menu_item(Id),
FOREIGN KEY(user_id) REFERENCES user(Id)
);
SHOW TABLES;

ALTER TABLE user
ADD COLUMN type VARCHAR(20);







